export const GET_POST_LIST = "GET_POST_LIST";
export const GET_POST_LIST_FAIL = "GET_POST_LIST_FAIL";
export const GET_POST_LIST_SUCCESS = "GET_POST_LIST_SUCCESS";

export const CREATE_POST_LIST = "CREATE_POST_LIST";
export const CREATE_POST_LIST_FAIL = "CREATE_POST_LIST_FAIL";
export const CREATE_POST_LIST_SUCCESS = "CREATE_POST_LIST_SUCCESS";

export const DELETE_POST_LIST = "DELETE_POST_LIST";
export const DELETE_POST_LIST_FAIL = "DELETE_POST_LIST_FAIL";
export const DELETE_POST_LIST_SUCCESS = "DELETE_POST_LIST_SUCCESS";
